package com.sparanzza.website.client.i18n;

import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.Constants;

// @GenerateKeys("com.sparanzza.website.server.i18n.WebsiteConstantsKeyGenerator")
// @Generate(format = "com.sparanzza.website.server.i18n.WebsiteConstantsCatalogFactory", locales = "default")
public interface WebsiteConstants extends Constants {

    WebsiteConstants I18N = GWT.create(WebsiteConstants.class);

    @Key("underConstruction") @DefaultStringValue("sparanzza.com esta todavia en construccion, actualizado 09/10/2020, ") String underConstruction();
    @Key("topTitleHome") @DefaultStringValue("Full Stack Java Dev & diseñador broadcast") String topTitleHome();
    @Key("topSubtitleHome") @DefaultStringValue("Me encata programar, y sobre todo diseñar cosas bonitas, amo lo que hago ;)") String topSubtitleHome();
    @Key("mainTextHome") @DefaultStringValue("Actualmente trabajo como Full Stack Java Developer pero con una trayectoria trayectoria en habilidades de diseño y desarrollo graficos en sistemas broadcast. Sparanzza no es solo un perfil más dentro de internet, es la historia de muchas etapas laborales, de múltiples vivencias adquiridas e innumerables adversidades superadas, pero lo más importante, es la suma del aprendizaje grandiosos compañeros, trabajo en equipo, apoyo y esfuerzo mutuo, de los cuales han hecho crecer no solo en lo profesional si no en lo personal, Sparanzza es en definitiva el cúmulo de experiencia adquirida a través del trabajo con la fuerza de la amistad. Por eso este sitio web es un homenaje a todas esas personas, que con su cariño, afecto y esfuerzo, han hecho maravillosa esta aventura.") String mainTextHome();

    @Key("lastStepsIntendia") @DefaultStringValue("<p>Desde finales de 2019 estoy empezando una nueva aventura como <strong>Full Stack developer</strong> con tecnologías Java y GWT y tecnológicas propias en la empresa <strong>Intendia</strong>, una compañía de Geotab, trabajando en nuevas características en su aplicación web para la gestión de <strong>Flotas de transportes, logistica y gestion de ficheros de tacógrafos</strong>. En mi aventura actual tengo la suerte de contar la gran ayuda de grandes amigos como Pedro Garcia, Alejandro Castilla o José Portillo, y no me olvido de <strong>Ignacio Baca</strong>, se que hemos discrepado en los modos y las ideas, puede que sea por nuestras diferentes experiencias en todos los niveles y ámbitos, pero quiero que sepas que aprecio, los momentos en los que sale esa persona docente y paciente, espero que sea todo esto reciproco para ambos, gracias por la oportunidad de participar en esta nueva aventura y el poder aprender tanto de vosotros.</p>") String lastStepsIntendia();
    @Key("lastStepsMissMotion") @DefaultStringValue("<p>En abril de 2018 pude afrontar un proyecto emocionante con la empresa Miss Motion como desarrollador en sistema broadcast con tecnología <strong>Vizrt</strong> en las elecciones electorales para el canal de <strong>televisión nacional TVE</strong> en la noche de elecciones generales de 2018 para la alimentación de datos para <strong>gráficos 3D y realidad aumentada</strong>. Lo más sorprendente de esta aventura no fue el haber participado en esta aventura tecnológica, sino el haber compartido esos momentos con grandísimos compañeros de laSexta el cual describiré mas adelante y son <strong>José Sancho, Laura Garzón y David Garcia</strong>.</p>") String lastStepsMissMotion();
    @Key("lastStepsGoldenRace") @DefaultStringValue("<p>Anteriormente trabajé casi 2 años desde 2018 como UI Designer Animator y programador en la empresa <strong>Golden Race Sport Betting virtual solutions</strong>, trabajando con tecnologías tales como <strong>Sketch, invision, Google web designer</strong> y trasladando las animaciones a tecnología <strong>Javascript y Angular</strong>. Durante esta época tengo que dar las gracias a muchas personas, entre ellos Santiago Manzi, Juan Rodríguez, Miguel Guillem y en especial a <strong>Manuel Sagall</strong>, una persona que siempre ha confiado siempre en mi y en mis habilidades, por lo que soy muy afortunado de conocer una gran amistad. <strong>Miguel Guillem</strong>, no me olvido de ti, gran jefe, profesional, es sin duda de los mejores profesionales UX que he conocido y sobre todo, ideas y objetivos claros, en definitiva un lider a seguir.</p>") String lastStepsGoldenRace();
    @Key("lastStepsCiclo") @DefaultStringValue("<p>A finales de 2017 terminé mi título de CFGS en desarrollo de aplicaciones informáticas, en modo telemático en el centro <strong>Ilerna</strong> el cual pude realizar mis prácticas de empresa durante 5 meses en la empresa <strong>Hostgreen SL</strong> en el Parque Tecnológico de Andalucía como mantenimiento de aplicaciones IOS con Objective-C además de PHP y MySQL para mantenimientos webs de clientes. Fue una gran experiencia mi paso por la empresa, agradecido por la oportunidad dada por <strong>Francisco Castilla</strong> y sobre todo un gran compañero de trabajo y amigo <strong>Ángel Jiménez</strong>. Durante estos momentos estoy aprendiendo otras tecnologías como <strong>Angular, Ionic, Firebase y MongoDB</strong> en proyectos personales que estoy desarrollando actualmente como son un juego llamado KUp, y la herramienta online opensource broadcast llamada <strong>Valholl RT</strong>.</p>") String lastStepsCiclo();
    @Key("lastStepsLasexta") @DefaultStringValue("<p>En el periodo de <strong>2010 - 20218</strong>, trabajé en <strong>laSexta</strong> la cual, fue una aventura <strong>inolvidable</strong>, durante estos 8 años, no solo he hecho innumerables proyectos, para la cadena de televisión privada laSexta, tales como desarrollo de <strong>líneas gráficas</strong> para los programas de televisión tales como laSexta Noticias, Jugones, Al rojo vivo, laSexta Noche entre otros, <strong>implantación de sistemas gráficos, desarrollo y automatización de procesos</strong>. \n" +
            "Durante este periodo estuve trabajando tecnologías tales como <strong>MySQL, scripting Vbs y plugins en C++</strong>, todo en torno a los software de la plataforma <strong>Vizrt</strong>, el cual pude sacar mis <strong>Certificado profesional en Vizrt Artist y Vizrt Trio</strong>. Grandes amigos me han acompañado en esta aventura, pero nunca me canso de decir que siempre daré gracias a <strong>Angel Rodriguez Campoy</strong> gran amigo el cual fue quien me ayudó a conseguir tal puesto de trabajo, además de ser un <strong>gran ilustrador</strong>, por no mencionar su gran sentido del humor, por mi parte Gracias!, pero además tengo que mencionar a más compañeros y hermanos de batalla, <strong>José Sancho, Laura Garzón, Alejandro Montals, Carlos Lugo,y muchos, muchos más</strong>.\n" +
            "Durante este periodo, además de mi trabajo, no dude en empezar a estudiar mi Ciclo Formativo de Grado Superior de Desarrollo de aplicaciones Informáticas. Esto no es un fin, te invito a visitar mi perfil para ver el resto de mis aptitudes.</p>") String lastStepsLasexta();

    @Key("handcrafted") @DefaultStringValue("Hecho a mano por mi") String handcrafted();
    @Key("nothingVentured") @DefaultStringValue("¡El que no arriesga, no gana!") String nothingVentured();
    @Key("madeWith") @DefaultStringValue("Hecho con") String madeWith();

    @Key("frontEnd") @DefaultStringValue("Front-End") String frontEnd();
    @Key("backEnd") @DefaultStringValue("Back-End") String backEnd();
    @Key("broadcast") @DefaultStringValue("Broadcast") String broadcast();
    @Key("designArt") @DefaultStringValue("diseño y arte") String designArt();
    @Key("integration") @DefaultStringValue("Integracion") String integration();

    @Key("hi") @DefaultStringValue("Hey!, soy Aurelio, encantado!") String hi();

    @Key("skillFrontHome") @DefaultStringValue("<p>Trato cada elemento de sus diseños basados en pantalla como componentes separados que pueden existir en otro lugar de un sitio web; fuera del contexto de sus composiciones de diseño. Con estos componentes produzco una <strong>guía de estilo</strong> que actúa como documento para una base de código reutilizable y <strong>mantenible</strong>. Todos los involucrados en un proyecto pueden confiar en una guía de estilo para comprender el lenguaje de un proyecto y producir una <strong>experiencia de usuario</strong> más consistente.</p>") String skillFrontHome();
    @Key("skillBackHome") @DefaultStringValue("<p>Trabajar la arquitectura interna de una web o aplicación móvil que va <strong>vinculado</strong> a todo el contenido (formularios, mapas, bases de datos, etc.) que se <strong>integrará</strong> con todo lo que ve el usuario final en una web o aplicación móvil. Anticiparse a posibles problemas que puedan surgir en la integración de elementos de una web o aplicación móvil y diseñará todas las soluciones necesarias para que el <strong>usuario final</strong> no tenga ningún inconveniente al utilizarlas.</p>") String skillBackHome();
    @Key("skillIntegrationHome") @DefaultStringValue("<p>Puedo unirme a su equipo de manera rápida y eficiente utilizando la integración continua con métodos y herramientas como <strong>Git</strong>, Jenkins, <strong>Agile / Scrum.</strong></p>") String skillIntegrationHome();
    @Key("skillBroadcastHome") @DefaultStringValue("<p>Diseño de <strong>branding</strong> de marcas, grafismos de televisión y postproducción de cine. puedo decir que mi especialidad entre los software mencionados anteriormente son Autodesk Maya y <strong>Vizrt siendo certificado Profesional</strong>. Actualmente me encuentro desarrollando un proyecto Open source llamado <strong>ValhollRT</strong> para el diseño de rotulación y gráficos 3D para <strong>Broadcast</strong>.</p>") String skillBroadcastHome();
    @Key("skillDesignHome") @DefaultStringValue("<p>Valoro la estructura de contenido simple, los patrones de diseño limpio y las interacciones bien pensadas. Lo que más disfruto diseñando es un buen <strong>UX y UI</strong>, aplicaciones web y móvil, y sobre todo un  logotipo impactante. Como desarrollador <strong>front-end</strong>, creo que es importante comprender tanto el diseño como el desarrollo para lograr un producto exitoso para el usuario. Puedo ayudar a producir un diseño limpio y funcional donde sea necesario.</p>") String skillDesignHome();

}